table functions
js2xxx/umi pull request #23
Opened 2023-04-01 06:52 UTC by IndifferentArea

2023-04-04 02:32 UTC, IndifferentArea commented
测试写不动，需要 `impl PageAlloc` 参数，不好搞

2023-04-04 11:41 UTC, js2xxx commented
帮你写好了测试用的PageAlloc：
```rust
use core::{alloc::{Layout, Allocator}, ptr::NonNull};

use alloc::alloc::Global;

use crate::{PAGE_SIZE, PageAlloc, Table};

const PAGE_LAYOUT: Layout = unsafe {
    Layout::from_size_align_unchecked(PAGE_SIZE, PAGE_SIZE)
};

struct Alloc;

unsafe impl PageAlloc for Alloc {
    fn alloc(&self) -> Option<NonNull<Table>> {
        Global.allocate(PAGE_LAYOUT).ok().map(NonNull::cast)
    }

    unsafe fn dealloc(&self, ptr: NonNull<Table>) {
        Global.deallocate(ptr.cast(), PAGE_LAYOUT)
    }
}
```
然后在lib.rs开头：
```rust
#![cfg_attr(test, feature(allocator_api))]

#[cfg(test)]
extern crate alloc;
```

2023-04-05 09:49 UTC, js2xxx requested changes

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +            // TEST: let ptr = addr.to_laddr(0);
还是加个参数这样比较好，反正传递常数会被优化掉：
```rust
pub fn table(&self, level: Level, id_offset: usize) -> Option<&Table> {
    // ...
    let ptr = addr.to_laddr(id_offset);
```
测试的时候：`entry.table(level, 0)`
实际使用：`entry.table(level, ID_OFFSET)`

或者变成泛型常量：
```rust
pub fn table<const I: usize>(&self, level: Level) -> Option<&Table> {
    // ...
    let ptr = addr.to_laddr(I);
```
测试的时候：`entry.table::<0>(level)`
实际使用：`entry.table::<ID_OFFSET>(level)`

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +            // TEST: let ptr = addr.to_laddr(0);
同上

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +            // TEST: let ptr = addr.to_laddr(0);
同上

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +            // TEST: let addr = LAddr::from(ptr).to_paddr(0);
同上

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +            // TEST: let ptr = addr.to_laddr(0);
同上

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +    /// mark and replace nearby similar codes with TEST_code.
用注释来切换测试是坏文明。在作了第一条评论的修改后就不需要把测试注释掉了。

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +    /// extern crate alloc;
这段定义测试用的`PageAlloc`代码直接放在`mod tests {`后面的开头，不需要放在这里。

2023-04-05 09:49 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        let mut touch_mark: BTreeSet<(Entry, Level)> = BTreeSet::new();
使用BTreeSet来记录访问过的页表需要额外的内存空间，感觉不是最优做法。建议是使用三重递归来操作。

每一层递归：
1. 遍历该页表所有被要unmap的区间覆盖到的entry。
2. 对于每一个entry：如果有没有子页表（或者当前level是`Level::pt()`），则直接reset，去5。
3. 如果有子页表，进入下一层递归（去1，传入新的`level = level.decrease()`）。
4. 判断该子页表是否空，如果是则回收页表内存，reset该entry。
5. 访问下一个entry，去2；遍历完则去6。
6. 返回上一层递归。

建议将该递归函数不设为pub，而是对其作简单的包装，包装函数去掉递归时候的参数（比如level）作为pub的对外接口。

2023-04-14 05:12 UTC, IndifferentArea commented
## TODO
1. review
2. modify other table functions to this way
3. add more test

2023-04-14 12:34 UTC, js2xxx requested changes

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +    pub fn table(&self, level: Level, magic_num: usize) -> Option<&Table> {
叫`magic_num`会不会太不易读了- -，就叫id_offset吧还是

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +    pub fn table_mut(&mut self, level: Level, magic_num: usize) -> Option<&mut Table> {
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +    pub fn la2pa(&mut self, la: LAddr, is_kernel: bool, magic_num: usize) -> Result<PAddr, Error> {
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        if begin_la.in_page_offset() != 0 || begin_la.in_page_offset() != 0 {
这里看起来应该是`begin_la`和`end_la`吧

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +                                        .0
不需要`.0`，因为已经`Deref`到`[Entry; 512]`了。

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +                                        .0
同上

2023-04-14 12:34 UTC, js2xxx commented on mizu/lib/paging/src/entry.rs
> +        magic_num: usize,
同上

2023-04-14 13:55 UTC, js2xxx approved these changes

2023-04-14 13:55 UTC, merged